version: '3'
services:
  prod:
    build: .
    volumes:
      - ./src:/app
      - ./node_modules:/node_modules
    env_file:
      - censorbot.env
    restart: unless-stopped
    ports:
      - "1234:1234"
  testing:
    build: .
    volumes:
      - ./src:/app
      - ./node_modules:/node_modules
    env_file:
      - censorbottesting.env
    restart: "no"
    ports:
      - "1235:1234"
  treehouse: # custom bot
    build: .
    volumes:
      - ./src:/app
      - ./node_modules:/node_modules
    env_file:
      - treehouse.env
    restart: unless-stopped
    ports:
      - "1236:1234"