version: '3'
services:
  prod:
    build: .
    volumes:
      - ./src:/app
      - /app/node_modules
    env_file:
      - censorbot.env
    restart: unless-stopped
    ports:
      - "1234:1234"
  testing:
    build: .
    volumes:
      - ./src:/app
      - /app/node_modules
    env_file:
      - censorbottesting.env
    restart: "no"
    ports:
      - "1235:1234"